"""Emit a validated Problem as a Pyomo model.

Pyomo is first because it is solver-agnostic: one emitter reaches HiGHS, CBC, SCIP, GLPK and the
commercial solvers, which means the backend choice stops being a translation decision and becomes a
runtime one.

Two properties this module holds to, both of them checks rather than intentions:

1. **Totality or refusal.** Every relation and objective in the problem is translated, or
   ``NotRepresentable`` is raised naming the construct. The model is assembled into a local object
   and only returned once every element has been translated, so a refusal leaves nothing behind.
2. **Units are checked before emission, not after.** Pyomo will happily add tonnes to seconds. The
   validator has already rejected that, and this emitter refuses to run on an invalid problem rather
   than trusting the caller to have validated it.

``build_model`` needs Pyomo installed (``pip install planteo[pyomo]``). ``emit_source`` does not: it
writes the equivalent Pyomo script as text, which is what the didactic surface displays and what a
reader can check by eye against the narrative.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

from ..expressions import (
    BigSum,
    Conditional,
    Constant,
    Expression,
    Power,
    Product,
    Ref,
    Sum,
)
from ..problem import Domain, Family, Problem, Role
from ..relations import Comparator, Compare, ForAll, Logical, Relation, Sense
from ..validate import ValidationError, validate
from . import NotRepresentable

BACKEND = "pyomo"

_DOMAIN_NAME = {
    Domain.REAL: "Reals",
    Domain.INTEGER: "Integers",
    Domain.BOOLEAN: "Binary",
}

_COMPARATOR_SOURCE = {
    Comparator.EQ: "==",
    Comparator.LE: "<=",
    Comparator.GE: ">=",
}


def _require_optimization(problem: Problem) -> None:
    if problem.family is not Family.OPTIMIZATION:
        raise NotRepresentable(
            f"the {problem.family.value} family", BACKEND, problem.metadata.problem_id
        )


def _require_valid(problem: Problem) -> None:
    report = validate(problem)
    if not report.ok:
        raise ValidationError(
            "refusing to emit an invalid problem; fix these first:\n  "
            + "\n  ".join(str(f) for f in report.errors)
        )


# -- source emission (no Pyomo needed) --------------------------------------------------


def emit_source(problem: Problem) -> str:
    """Write the problem as a runnable Pyomo script.

    This is the artifact a reader checks against the narrative, so it carries the provenance: each
    declaration is preceded by the words it came from.
    """
    _require_optimization(problem)
    _require_valid(problem)

    lines: list[str] = [
        '"""Generated by planteo from a narrative problem statement.',
        "",
        "Every declaration below cites the span of narrative it came from. An element marked",
        "inferred was not read from the text; the reason is given.",
        '"""',
        "",
        "import pyomo.environ as pyo",
        "",
        "model = pyo.ConcreteModel()",
        "",
    ]

    if problem.metadata.title:
        lines.insert(0, f"# {problem.metadata.title}")

    for question in problem.open_questions:
        marker = "OPEN" if question.is_open else "resolved"
        lines.append(f"# [{marker}] {question.question}")
        if not question.is_open:
            lines.append(f"#          {question.resolution}")
    if problem.open_questions:
        lines.append("")

    for quantity in problem.quantities:
        lines.extend(_provenance_comment(quantity.span, quantity.description))
        if quantity.role is Role.SET:
            lines.append(f"model.{quantity.name} = pyo.Set(initialize=[])  # supply members")
        elif quantity.role is Role.PARAMETER:
            value = "None" if quantity.value is None else repr(quantity.value)
            lines.append(
                f"model.{quantity.name} = pyo.Param(initialize={value}, mutable=True)"
                f"  # {quantity.dimension.describe()}"
            )
        else:
            domain = _domain_name(quantity)
            bounds = f", bounds=({_bound(quantity.lower)}, {_bound(quantity.upper)})"
            lines.append(
                f"model.{quantity.name} = pyo.Var(domain=pyo.{domain}{bounds})"
                f"  # {quantity.dimension.describe()}"
            )
        lines.append("")

    for index, relation in enumerate(problem.relations):
        name = getattr(relation, "name", "") or f"constraint_{index}"
        lines.extend(_provenance_comment(getattr(relation, "span", None), ""))
        lines.append(f"model.{name} = pyo.Constraint(expr={_relation_source(relation, name)})")
        lines.append("")

    for objective in problem.objectives:
        sense = "pyo.minimize" if objective.sense is Sense.MINIMISE else "pyo.maximize"
        lines.extend(_provenance_comment(objective.span, ""))
        lines.append(
            f"model.{objective.name} = pyo.Objective("
            f"expr={_expression_source(objective.expression, objective.name)}, sense={sense})"
        )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _provenance_comment(span: Any, description: str) -> list[str]:
    out: list[str] = []
    if description:
        out.append(f"# {description}")
    if span is None:
        out.append("# (no provenance recorded)")
    elif span.is_inferred:
        out.append(f"# inferred: {span.inferred_reason}")
    else:
        out.append(f'# from the narrative: "{span.text}"')
    return out


def _domain_name(quantity: Any) -> str:
    try:
        return _DOMAIN_NAME[quantity.domain]
    except KeyError:
        raise NotRepresentable(
            f"the {quantity.domain.value} domain", BACKEND, quantity.name
        ) from None


def _bound(value: float | None) -> str:
    return "None" if value is None else repr(value)


def _relation_source(relation: Relation, element: str) -> str:
    if isinstance(relation, Compare):
        try:
            operator = _COMPARATOR_SOURCE[relation.comparator]
        except KeyError:
            raise NotRepresentable(
                f"the comparator {relation.comparator.value!r}", BACKEND, element
            ) from None
        left = _expression_source(relation.left, element)
        right = _expression_source(relation.right, element)
        return f"{left} {operator} {right}"
    if isinstance(relation, ForAll):
        raise NotRepresentable(
            "an indexed constraint family (use an indexed Constraint rule)", BACKEND, element
        )
    if isinstance(relation, Logical):
        raise NotRepresentable(
            f"the logical connective {relation.connective!r} "
            "(it needs a disjunctive reformulation or pyomo.gdp)",
            BACKEND,
            element,
        )
    raise NotRepresentable(f"the relation node {relation.tag!r}", BACKEND, element)


def _expression_source(expression: Expression, element: str) -> str:
    if isinstance(expression, Constant):
        return repr(expression.value)
    if isinstance(expression, Ref):
        return f"model.{expression.name}"
    if isinstance(expression, Sum):
        return "(" + " + ".join(_expression_source(t, element) for t in expression.terms) + ")"
    if isinstance(expression, Product):
        return "(" + " * ".join(_expression_source(f, element) for f in expression.factors) + ")"
    if isinstance(expression, Power):
        base = _expression_source(expression.base, element)
        return f"({base} ** {float(expression.exponent)!r})"
    if isinstance(expression, BigSum):
        body = _expression_source(expression.body, element)
        return (
            f"sum({body} for {expression.index} in model.{expression.index_set})"
        )
    if isinstance(expression, Conditional):
        raise NotRepresentable(
            "a conditional expression (it needs a big-M or indicator reformulation)",
            BACKEND,
            element,
        )
    raise NotRepresentable(f"the expression node {expression.tag!r}", BACKEND, element)


# -- live model construction (needs Pyomo) ----------------------------------------------


def build_model(problem: Problem) -> Any:
    """Build a ``pyomo.environ.ConcreteModel``.

    The model is assembled completely before it is returned, so a ``NotRepresentable`` raised
    part-way leaves no half-built object in the caller's hands.
    """
    _require_optimization(problem)
    _require_valid(problem)

    try:
        import pyomo.environ as pyo
    except ImportError as error:  # pragma: no cover, exercised only without the extra
        raise ImportError(
            "building a live model needs Pyomo: pip install 'planteo[pyomo]'"
        ) from error

    model = pyo.ConcreteModel(name=problem.metadata.title or "planteo")
    resolve: dict[str, Any] = {}

    for quantity in problem.quantities:
        if quantity.role is Role.SET:
            component = pyo.Set(initialize=[])
        elif quantity.role is Role.PARAMETER:
            component = pyo.Param(
                initialize=quantity.value, mutable=True, within=pyo.Any
            )
        else:
            domain = getattr(pyo, _domain_name(quantity))
            component = pyo.Var(
                domain=domain, bounds=(quantity.lower, quantity.upper)
            )
        setattr(model, quantity.name, component)
        resolve[quantity.name] = getattr(model, quantity.name)

    for index, relation in enumerate(problem.relations):
        name = getattr(relation, "name", "") or f"constraint_{index}"
        setattr(model, name, pyo.Constraint(expr=_relation_value(relation, resolve, name)))

    for objective in problem.objectives:
        sense = pyo.minimize if objective.sense is Sense.MINIMISE else pyo.maximize
        setattr(
            model,
            objective.name,
            pyo.Objective(
                expr=_expression_value(objective.expression, resolve, objective.name),
                sense=sense,
            ),
        )

    return model


def _relation_value(relation: Relation, resolve: dict[str, Any], element: str) -> Any:
    if isinstance(relation, Compare):
        left = _expression_value(relation.left, resolve, element)
        right = _expression_value(relation.right, resolve, element)
        operator: Callable[[Any, Any], Any] = {
            Comparator.EQ: lambda a, b: a == b,
            Comparator.LE: lambda a, b: a <= b,
            Comparator.GE: lambda a, b: a >= b,
        }.get(relation.comparator)  # type: ignore[assignment]
        if operator is None:
            raise NotRepresentable(
                f"the comparator {relation.comparator.value!r}", BACKEND, element
            )
        return operator(left, right)
    # Everything else refuses for the same reasons as the source emitter.
    return _relation_source(relation, element)  # raises NotRepresentable


def _expression_value(expression: Expression, resolve: dict[str, Any], element: str) -> Any:
    if isinstance(expression, Constant):
        return expression.value
    if isinstance(expression, Ref):
        try:
            return resolve[expression.name]
        except KeyError:
            raise NotRepresentable(
                f"a reference to {expression.name!r}", BACKEND, element
            ) from None
    if isinstance(expression, Sum):
        total = _expression_value(expression.terms[0], resolve, element)
        for term in expression.terms[1:]:
            total = total + _expression_value(term, resolve, element)
        return total
    if isinstance(expression, Product):
        result = _expression_value(expression.factors[0], resolve, element)
        for factor in expression.factors[1:]:
            result = result * _expression_value(factor, resolve, element)
        return result
    if isinstance(expression, Power):
        return _expression_value(expression.base, resolve, element) ** float(
            expression.exponent
        )
    # BigSum over an empty set and Conditional both refuse, via the source path.
    return _expression_source(expression, element)  # raises NotRepresentable
